"""
Pydantic models for clothing item attributes and the wardrobe catalog.

Used by:
- gemini_tagger.py: structured output schema for Gemini
- github_writer.py: wardrobe.json catalog shape
- pipeline.py: merging and validation
"""

from datetime import date
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Category Enums ───────────────────────────────────────────────────────────

class Category(str, Enum):
    """Clothing categories. Each maps to a 2-letter ID prefix in id_registry."""

    FULL_SLEEVE_SHIRT = "full_sleeve_shirt"
    HALF_SLEEVE_SHIRT = "half_sleeve_shirt"
    T_SHIRT = "t_shirt"
    POLO = "polo"
    TANK_TOP = "tank_top"
    JEANS = "jeans"
    TROUSERS = "trousers"
    SHORTS = "shorts"
    JACKET = "jacket"
    BLAZER = "blazer"
    HOODIE = "hoodie"
    SWEATSHIRT = "sweatshirt"
    DRESS = "dress"
    SKIRT = "skirt"
    OTHER = "other"


class SleeveType(str, Enum):
    FULL = "full"
    HALF = "half"
    THREE_QUARTER = "three_quarter"
    SLEEVELESS = "sleeveless"
    SHORT = "short"
    NOT_APPLICABLE = "n/a"


class Fit(str, Enum):
    REGULAR = "regular"
    SLIM = "slim"
    LOOSE = "loose"
    OVERSIZED = "oversized"
    TAPERED = "tapered"
    STRAIGHT = "straight"
    NOT_VISIBLE = "not_visible"


class Pattern(str, Enum):
    NONE = "none"
    STRIPED = "striped"
    PLAID = "plaid"
    CHECKED = "checked"
    FLORAL = "floral"
    GRAPHIC_PRINT = "graphic_print"
    SOLID = "solid"
    DENIM = "denim"
    CAMOUFLAGE = "camouflage"
    POLKA_DOT = "polka_dot"
    OTHER = "other"


# ─── Gemini Output Schema ────────────────────────────────────────────────────

class GarmentAttributes(BaseModel):
    """
    Structured attributes for a single garment, as returned by Gemini.

    This is the schema sent to Gemini for structured JSON output.
    The model must NEVER generate an ID — that's handled by id_registry.
    """

    category: Category = Field(
        description="The primary clothing category of the garment."
    )
    sleeve_type: SleeveType = Field(
        description="Sleeve length type. Use 'n/a' for items without sleeves (e.g. trousers)."
    )
    color: str = Field(
        description="Primary color description, e.g. 'dark grey', 'navy blue', 'off-white'."
    )
    pattern: Pattern = Field(
        description="Pattern type. Use 'none' for solid single-color garments."
    )
    fit: Fit = Field(
        description="How the garment fits. Use 'not_visible' if the photo doesn't show fit clearly."
    )
    material_guess: str = Field(
        description="Best guess at the material/fabric, e.g. 'cotton', 'denim', 'wool blend', 'linen'."
    )
    notes: str = Field(
        default="",
        description="Additional observations: collar type, pockets, logos, distinctive features, condition notes.",
    )


# ─── Catalog Schema (wardrobe.json) ──────────────────────────────────────────

class WardrobeItem(BaseModel):
    """
    A single item in the wardrobe catalog (wardrobe.json).

    Includes the Gemini-extracted attributes plus pipeline-generated fields
    (id, image_url, date_added).
    """

    id: str = Field(description="Deterministic ID like FS04, TR02 — generated by the pipeline, never by Gemini.")
    category: str = Field(description="Category string value from the Category enum.")
    color: str = Field(description="Primary color description.")
    pattern: str = Field(description="Pattern type.")
    sleeve_type: str = Field(description="Sleeve length type.")
    fit: str = Field(description="Fit description.")
    material_guess: str = Field(description="Guessed material/fabric.")
    notes: str = Field(default="", description="Additional observations.")
    image_url: str = Field(description="Full raw.githubusercontent.com URL for the item's image.")
    date_added: str = Field(description="Date the item was added to the catalog, ISO format (YYYY-MM-DD).")


class WardrobeCatalog(BaseModel):
    """
    The top-level wardrobe.json catalog schema.
    """

    items: list[WardrobeItem] = Field(
        default_factory=list,
        description="All cataloged wardrobe items."
    )

    def get_item_by_id(self, item_id: str) -> Optional[WardrobeItem]:
        """Look up an item by its ID."""
        for item in self.items:
            if item.id == item_id:
                return item
        return None

    def existing_ids(self) -> set[str]:
        """Return the set of all item IDs currently in the catalog."""
        return {item.id for item in self.items}

    def merge_items(self, new_items: list[WardrobeItem]) -> list[WardrobeItem]:
        """
        Merge new items into the catalog.

        New items are appended. Items whose ID already exists in the catalog
        are skipped (never overwrite). Returns the list of items that were
        actually added.

        Args:
            new_items: Items to add to the catalog.

        Returns:
            List of items that were actually appended (excludes duplicates).
        """
        existing = self.existing_ids()
        added = []
        for item in new_items:
            if item.id in existing:
                import logging
                logging.getLogger(__name__).warning(
                    f"Skipping duplicate ID {item.id} — already in catalog"
                )
                continue
            self.items.append(item)
            existing.add(item.id)
            added.append(item)
        return added


def load_catalog_from_json(json_str: str) -> WardrobeCatalog:
    """
    Parse a wardrobe.json string into a WardrobeCatalog.

    Args:
        json_str: JSON string from the GitHub repo.

    Returns:
        WardrobeCatalog instance. Returns empty catalog if JSON is invalid.
    """
    import json as _json

    try:
        data = _json.loads(json_str)
        return WardrobeCatalog.model_validate(data)
    except (_json.JSONDecodeError, Exception) as e:
        import logging
        logging.getLogger(__name__).warning(
            f"Could not parse wardrobe.json, starting with empty catalog: {e}"
        )
        return WardrobeCatalog()


def catalog_to_json(catalog: WardrobeCatalog) -> str:
    """
    Serialize a WardrobeCatalog to pretty-printed JSON.

    Args:
        catalog: The catalog to serialize.

    Returns:
        JSON string.
    """
    return catalog.model_dump_json(indent=2)


# ─── Tagging Result ──────────────────────────────────────────────────────────

class TaggingResult(BaseModel):
    """
    Result of tagging a single image, including metadata.
    """

    drive_file_id: str
    drive_filename: str
    attributes: GarmentAttributes
    needs_manual_review: bool = False
    review_reason: Optional[str] = None
