"""
Pydantic models for clothing item attributes and the wardrobe catalog.

Used by:
- gemini_tagger.py: structured output schema for Gemini
- github_writer.py: wardrobe.json catalog shape
- pipeline.py: merging and validation
"""

from datetime import date
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Category Enums ───────────────────────────────────────────────────────────

class Category(str, Enum):
    """Clothing categories. Each maps to a 2-letter ID prefix in id_registry."""

    FULL_SLEEVE_SHIRT = "full_sleeve_shirt"
    HALF_SLEEVE_SHIRT = "half_sleeve_shirt"
    T_SHIRT = "t_shirt"
    POLO = "polo"
    TANK_TOP = "tank_top"
    JEANS = "jeans"
    TROUSERS = "trousers"
    SHORTS = "shorts"
    JACKET = "jacket"
    BLAZER = "blazer"
    HOODIE = "hoodie"
    SWEATSHIRT = "sweatshirt"
    DRESS = "dress"
    SKIRT = "skirt"
    OTHER = "other"


class SleeveType(str, Enum):
    FULL = "full"
    HALF = "half"
    THREE_QUARTER = "three_quarter"
    SLEEVELESS = "sleeveless"
    SHORT = "short"
    NOT_APPLICABLE = "n/a"


class Fit(str, Enum):
    REGULAR = "regular"
    SLIM = "slim"
    LOOSE = "loose"
    OVERSIZED = "oversized"
    TAPERED = "tapered"
    STRAIGHT = "straight"
    NOT_VISIBLE = "not_visible"


class Pattern(str, Enum):
    NONE = "none"
    STRIPED = "striped"
    PLAID = "plaid"
    CHECKED = "checked"
    FLORAL = "floral"
    GRAPHIC_PRINT = "graphic_print"
    SOLID = "solid"
    DENIM = "denim"
    CAMOUFLAGE = "camouflage"
    POLKA_DOT = "polka_dot"
    OTHER = "other"


# ─── Gemini Output Schema ────────────────────────────────────────────────────

class GarmentAttributes(BaseModel):
    """
    Structured attributes for a single garment, as returned by Gemini.

    This is the schema sent to Gemini for structured JSON output.
    The model must NEVER generate an ID — that's handled by id_registry.
    """

    category: Category = Field(
        description="The primary clothing category of the garment."
    )
    sleeve_type: SleeveType = Field(
        description="Sleeve length type. Use 'n/a' for items without sleeves (e.g. trousers)."
    )
    color: str = Field(
        description="Primary color description, e.g. 'dark grey', 'navy blue', 'off-white'."
    )
    pattern: Pattern = Field(
        description="Pattern type. Use 'none' for solid single-color garments."
    )
    fit: Fit = Field(
        description="How the garment fits. Use 'not_visible' if the photo doesn't show fit clearly."
    )
    material_guess: str = Field(
        description="Best guess at the material/fabric, e.g. 'cotton', 'denim', 'wool blend', 'linen'."
    )
    notes: str = Field(
        default="",
        description="Additional observations: collar type, pockets, logos, distinctive features, condition notes.",
    )


# ─── Catalog Schema (wardrobe.json) ──────────────────────────────────────────

class WardrobeItem(BaseModel):
    """
    A single item in the wardrobe catalog (wardrobe.json).

    Includes the Gemini-extracted attributes plus pipeline-generated fields
    (id, image_url, date_added).
    """

    id: str = Field(description="Deterministic ID like FS04, TR02 — generated by the pipeline, never by Gemini.")
    category: str = Field(description="Category string value from the Category enum.")
    color: str = Field(description="Primary color description.")
    pattern: str = Field(description="Pattern type.")
    sleeve_type: str = Field(description="Sleeve length type.")
    fit: str = Field(description="Fit description.")
    material_guess: str = Field(description="Guessed material/fabric.")
    notes: str = Field(default="", description="Additional observations.")
    image_url: str = Field(description="Full raw.githubusercontent.com URL for the item's image.")
    date_added: str = Field(description="Date the item was added to the catalog, ISO format (YYYY-MM-DD).")


class WardrobeCatalog(BaseModel):
    """
    The top-level wardrobe.json catalog schema.
    """

    items: list[WardrobeItem] = Field(
        default_factory=list,
        description="All cataloged wardrobe items."
    )


# ─── Tagging Result ──────────────────────────────────────────────────────────

class TaggingResult(BaseModel):
    """
    Result of tagging a single image, including metadata.
    """

    drive_file_id: str
    drive_filename: str
    attributes: GarmentAttributes
    needs_manual_review: bool = False
    review_reason: Optional[str] = None
